
POST http://localhost:8080/events
Content-Type: application/json

{
  "name": "Test Event",
  "description": "A test event",
  "location": "A test location",
  "dateTime": "{{$datetime iso8601}}"
}

